### ISSUE TITLE
Markers Function

### ISSUE THREAD

**Issue by oyeb2003** [johnsonra/JoesFlow#7]
I get this error code anytime I use the "marker" function/tab under visualize in order to try to generate the heat map.  I have added the screen shot here as well. 

rsession: UnableToOpenBlob `/var/folders/_x/0xd22ybx1pnb_rjhmtd1r801bm3nm8/T//RtmpRn2iIY/.heatmap_body_846b848a76c3afd8199b0903d87e964b_1_116d5645c7a91f.png': No such file or directory @ error/blob.c/OpenBlob/2924

Warning: Error in magick_image_readpath: rsession: UnableToOpenBlob `/var/folders/_x/0xd22ybx1pnb_rjhmtd1r801bm3nm8/T//RtmpRn2iIY/.heatmap_body_455ed3f7aff9d8d0c92266c9de67e33f_1_116d56465efb43.png': No such file or directory @ error/blob.c/OpenBlob/2924
  198: <Anonymous
<img width="1292" alt="Screen Shot 2022-05-27 at 4 42 05 PM" src="https://user-images.githubusercontent.com/79373782/170786870-d22eebee-0295-49b7-a7b1-80e50dd41dbe.png">

<img width="924" alt="Screen Shot 2022-05-27 at 4 42 45 PM" src="https://user-images.githubusercontent.com/79373782/170786861-58e4d0b9-a57a-4e35-b22f-1cdbb91b7b49.png">
>

**Comment by johnsonra** [comment]
This appears to be a system configuration problem, as I can't replicate this error on my system. Planning to use a Docker container to make system configuration easier.
